apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "dra-driver-memory.fullname" . }}-kubeletplugin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dra-driver-memory.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dra-driver-memory.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "dra-driver-memory.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.daemonset.priorityClassName }}
      serviceAccountName: {{ include "dra-driver-memory.serviceAccountName" . }}
      {{- with .Values.daemonset.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: plugin
        securityContext:
          {{- toYaml .Values.daemonset.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          {{- toYaml .Values.daemonset.command | nindent 10 }}
        env:
        - name: CDI_ROOT
          value: {{ .Values.daemonset.env.cdiRoot | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NUM_DEVICES
          value: {{ .Values.daemonset.env.numDevices | quote }}
        volumeMounts:
        - name: plugins-registry
          mountPath: {{ .Values.daemonset.volumes.pluginsRegistry }}
        - name: plugins
          mountPath: {{ .Values.daemonset.volumes.plugins }}
        - name: cdi
          mountPath: {{ .Values.daemonset.volumes.cdi }}
      volumes:
      - name: plugins-registry
        hostPath:
          path: {{ .Values.daemonset.volumes.pluginsRegistry }}
      - name: plugins
        hostPath:
          path: {{ .Values.daemonset.volumes.plugins }}
      - name: cdi
        hostPath:
          path: {{ .Values.daemonset.volumes.cdi }}

