{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dra-driver-memory.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dra-driver-memory.labels" . | nindent 4 }}
{{- end }}

